services:
  db:
    image: postgres:12.13-bullseye
    restart: always
    container_name: pg
    # logging:
    #   driver: json-file
    #   options:
    #     max-file: "1"
    #     max-size: 3m
    environment:
      POSTGRES_PASSWORD: pass_admin
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    ports:
      - 5432:5432
  redis:
    image: redis:7.0-bullseye
    restart: always
    container_name: re
    command: redis-server /etc/redis/redis.conf
    ports:
      - 6379:6379
    volumes:
      - ./redis_data/:/data
      - "./redis.conf:/etc/redis/redis.conf"
      - "./server.crt:/etc/redis/server.crt"
      - "./server.key:/etc/redis/server.key"

volumes:
  postgres_volume:
